---
#task to build docker containers
- name: Deploy docker containers
  hosts: 'docker_server'
  become: true
  vars: vars/docker-vars.yml
  tasks:
    - name: Build the docker image
      command: docker build -t '{{ docker_hub_username }}/{{ docker_hub_repo }}:{{ docker_hub_tag }}' '{{ dockerfile_path }}'
      when: (bw_cmd is defined)  and (bw_cmd == "build") and docker_hub_username is defined and docker_hub_repo is defined and docker_hub_tag is defined and dockerfile_path is defined

    - name: Push to docker registry
      command: docker push '{{ docker_hub_username }}/{{ docker_hub_repo }}:{{ docker_hub_tag }}'
      when: (bw_cmd is defined)  and (bw_cmd == "push") and docker_hub_username is defined and docker_hub_repo is defined and docker_hub_tag is defined

