---
#task to control docker containers
- name: Control docker containers
  hosts: '{{ ip_address | default("all") }}'
  become: true
  tasks:
    - name: Restart docker container
      command: docker restart '{{ container_name }}'
      when: docker_container is defined


