---
#task to control docker containers
- name: Control docker containers
  hosts: '{{ ip_address | default("all") }}'
  become: true
  tasks:
    - name: Restart docker container
      docker_container:
          name: '{{ container_name }}'
          state: restarted

