---
#task to control docker containers
- name: Control docker containers
  hosts: '{{ ip_address | default("all") }}'
  become: true
  include_vars: vars/docker-vars.yml
  tasks:
    - name: Restart docker container
      command: docker restart '{{ container_name }}'
      when: (bw_cmd is defined)  and (bw_cmd == "restart") and container_name is defined

    - name: Stop docker container
      command: docker stop '{{ container_name }}'
      when: (bw_cmd is defined)  and (bw_cmd == "stop") and container_name is defined

    - name: Start docker container
      command: docker start '{{ container_name }}'
      when: (bw_cmd is defined)  and (bw_cmd == "start") and container_name is defined

    - name: install npm package in the docker container
      command: docker exec '{{ container_name }}' npm install '{{ npm_package }}'
      when: (bw_cmd is defined)  and (bw_cmd == "npm_install") and container_name is defined and npm_package is defined

    - name: Build container for live and push to docker hub
      include_tasks: include_task/build-push.yml
      when: (bw_cmd is defined)  and (bw_cmd == "build")

    - name: Deploy container on the swarm
      include_tasks: include_task/deploy-swarm.yml
      when: (bw_cmd is defined)  and (bw_cmd == "deploy")